import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import { provideNzI18n, zh_CN } from 'ng-zorro-antd/i18n';
import { provideNzConfig } from 'ng-zorro-antd/core/config';
import { LOCALE_ID } from '@angular/core';
import { registerLocaleData } from '@angular/common';
import zh from '@angular/common/locales/zh';

registerLocaleData(zh);
import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  AppstoreOutline,
  ArrowRightOutline,
  ArrowLeftOutline,
  CloudUploadOutline,
  CloudFill,
  UndoOutline,
  DatabaseOutline,
  DatabaseFill,
  SettingOutline,
  SaveOutline,
  CalendarOutline,
  CheckOutline,
  FileTextOutline,
  HddOutline,
  DeploymentUnitOutline,
  DashboardOutline,
  SlidersOutline,
  ProfileOutline,
  FileSearchOutline,
  HistoryOutline,
  ToolOutline,
  ReloadOutline,
  RedoOutline,
  LoadingOutline,
  SyncOutline,
  CloudDownloadOutline,
  CloudServerOutline,
  InboxOutline,
  SafetyOutline,
  SafetyCertificateOutline,
  GlobalOutline,
  ClockCircleOutline,
  CheckCircleOutline,
  ExclamationCircleOutline,
  CloseCircleOutline,
  CloseOutline,
  PlusOutline,
  MoreOutline,
  EyeOutline,
  EditOutline,
  DeleteOutline,
  InfoCircleOutline,
  PlayCircleOutline,
  CopyOutline,
  DownloadOutline,
  LinkOutline,
  SearchOutline,
  NotificationOutline,
  BellOutline,
  LoginOutline,
  LogoutOutline,
  WarningOutline,
  AuditOutline,
  LeftOutline,
  RightOutline,
  CloudOutline,
  ShareAltOutline,
  FilterOutline,
  DownOutline,
  TagOutline,
  BookOutline,
  ClusterOutline,
  DatabaseOutline as DbOutline,
  FieldTimeOutline,
  QuestionCircleOutline,
  ExportOutline,
  SettingTwoTone,
  BugOutline,
  BuildOutline,
  MinusCircleOutline,
  PlusCircleOutline,
  RocketOutline,
  ThunderboltOutline,
  CodeOutline,
  DesktopOutline,
  ControlOutline
} from '@ant-design/icons-angular/icons';
import { PauseOutline, ExperimentOutline, LineChartOutline, BarChartOutline, FileAddOutline, HeartOutline } from '@ant-design/icons-angular/icons';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }), 
    provideRouter(routes),
    provideHttpClient(withInterceptors([
      (req, next) => {
        const token = localStorage.getItem('jwtToken');
        if (token && req.url.includes('/api/v1/') && !req.headers.has('Authorization')) {
          req = req.clone({ setHeaders: { Authorization: `Bearer ${token}` } });
        }
        return next(req);
      }
    ])),
    provideNoopAnimations(),
    provideNzI18n(zh_CN),
    { provide: LOCALE_ID, useValue: 'zh-cn' },
    provideNzConfig({
      tabs: { nzAnimated: false }
    }),
    provideNzIcons([
      MenuFoldOutline,
      MenuUnfoldOutline,
      AppstoreOutline,
      ArrowRightOutline,
      ArrowLeftOutline,
      CloudUploadOutline,
      CloudFill,
      UndoOutline,
      DatabaseOutline,
      DatabaseFill,
      SettingOutline,
      SaveOutline,
      CalendarOutline,
      CheckOutline,
      FileTextOutline,
      HddOutline,
      DeploymentUnitOutline,
      DashboardOutline,
      SlidersOutline,
      ProfileOutline,
      FileSearchOutline,
      HistoryOutline,
      ToolOutline,
      ReloadOutline,
      RedoOutline,
      LoadingOutline,
      SyncOutline,
      CloudDownloadOutline,
      CloudServerOutline,
      InboxOutline,
      SafetyOutline,
      SafetyCertificateOutline,
      GlobalOutline,
      ClockCircleOutline,
      CheckCircleOutline,
      ExclamationCircleOutline,
      CloseCircleOutline,
      CloseOutline,
      PlusOutline,
      MoreOutline,
      EyeOutline,
      EditOutline,
      DeleteOutline,
      InfoCircleOutline,
      PlayCircleOutline,
      CopyOutline,
      DownloadOutline,
      LinkOutline,
      SearchOutline,
      NotificationOutline,
      BellOutline,
      LoginOutline,
      LogoutOutline,
      WarningOutline,
      AuditOutline,
      LeftOutline,
      RightOutline,
      CloudOutline,
      ShareAltOutline,
      FilterOutline,
      DownOutline,
      TagOutline,
      BookOutline,
      ClusterOutline,
      DbOutline,
      FieldTimeOutline,
      QuestionCircleOutline,
      ExportOutline,
      SettingTwoTone,
      BugOutline,
      BuildOutline,
      MinusCircleOutline,
      PlusCircleOutline,
      RocketOutline,
      ThunderboltOutline,
      CodeOutline,
      DesktopOutline,
      ControlOutline,
      PauseOutline,
      ExperimentOutline,
      LineChartOutline,
      BarChartOutline,
      FileAddOutline,
      HeartOutline
    ])
  ]
};
