//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 Alibaba Group Holding Limited.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/alibaba/polardbx-operator/api/v1/polardbx"
	"github.com/alibaba/polardbx-operator/api/v1/systemtask"
	"github.com/alibaba/polardbx-operator/api/v1/xstore"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowFlagType) DeepCopyInto(out *FlowFlagType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowFlagType.
func (in *FlowFlagType) DeepCopy() *FlowFlagType {
	if in == nil {
		return nil
	}
	out := new(FlowFlagType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogCollectorConfigStatus) DeepCopyInto(out *LogCollectorConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogCollectorConfigStatus.
func (in *LogCollectorConfigStatus) DeepCopy() *LogCollectorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LogCollectorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogCollectorSpec) DeepCopyInto(out *LogCollectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogCollectorSpec.
func (in *LogCollectorSpec) DeepCopy() *LogCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(LogCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogCollectorStatus) DeepCopyInto(out *LogCollectorStatus) {
	*out = *in
	if in.ConfigStatus != nil {
		in, out := &in.ConfigStatus, &out.ConfigStatus
		*out = new(LogCollectorConfigStatus)
		**out = **in
	}
	if in.SpecSnapshot != nil {
		in, out := &in.SpecSnapshot, &out.SpecSnapshot
		*out = new(LogCollectorSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogCollectorStatus.
func (in *LogCollectorStatus) DeepCopy() *LogCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(LogCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParamNode) DeepCopyInto(out *ParamNode) {
	*out = *in
	if in.ParamList != nil {
		in, out := &in.ParamList, &out.ParamList
		*out = make([]Params, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParamNode.
func (in *ParamNode) DeepCopy() *ParamNode {
	if in == nil {
		return nil
	}
	out := new(ParamNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParamNodeType) DeepCopyInto(out *ParamNodeType) {
	*out = *in
	in.CN.DeepCopyInto(&out.CN)
	in.DN.DeepCopyInto(&out.DN)
	if in.GMS != nil {
		in, out := &in.GMS, &out.GMS
		*out = new(ParamNode)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParamNodeType.
func (in *ParamNodeType) DeepCopy() *ParamNodeType {
	if in == nil {
		return nil
	}
	out := new(ParamNodeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Params) DeepCopyInto(out *Params) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Params.
func (in *Params) DeepCopy() *Params {
	if in == nil {
		return nil
	}
	out := new(Params)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackup) DeepCopyInto(out *PolarDBXBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackup.
func (in *PolarDBXBackup) DeepCopy() *PolarDBXBackup {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupBinlog) DeepCopyInto(out *PolarDBXBackupBinlog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupBinlog.
func (in *PolarDBXBackupBinlog) DeepCopy() *PolarDBXBackupBinlog {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupBinlog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXBackupBinlog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupBinlogList) DeepCopyInto(out *PolarDBXBackupBinlogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXBackupBinlog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupBinlogList.
func (in *PolarDBXBackupBinlogList) DeepCopy() *PolarDBXBackupBinlogList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupBinlogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXBackupBinlogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupBinlogSpec) DeepCopyInto(out *PolarDBXBackupBinlogSpec) {
	*out = *in
	out.RemoteExpireLogHours = in.RemoteExpireLogHours
	out.LocalExpireLogHours = in.LocalExpireLogHours
	out.StorageProvider = in.StorageProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupBinlogSpec.
func (in *PolarDBXBackupBinlogSpec) DeepCopy() *PolarDBXBackupBinlogSpec {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupBinlogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupBinlogStatus) DeepCopyInto(out *PolarDBXBackupBinlogStatus) {
	*out = *in
	if in.LastDeletedFiles != nil {
		in, out := &in.LastDeletedFiles, &out.LastDeletedFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupBinlogStatus.
func (in *PolarDBXBackupBinlogStatus) DeepCopy() *PolarDBXBackupBinlogStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupBinlogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupList) DeepCopyInto(out *PolarDBXBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupList.
func (in *PolarDBXBackupList) DeepCopy() *PolarDBXBackupList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupSchedule) DeepCopyInto(out *PolarDBXBackupSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupSchedule.
func (in *PolarDBXBackupSchedule) DeepCopy() *PolarDBXBackupSchedule {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXBackupSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupScheduleList) DeepCopyInto(out *PolarDBXBackupScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXBackupSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupScheduleList.
func (in *PolarDBXBackupScheduleList) DeepCopy() *PolarDBXBackupScheduleList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXBackupScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupScheduleSpec) DeepCopyInto(out *PolarDBXBackupScheduleSpec) {
	*out = *in
	out.BackupSpec = in.BackupSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupScheduleSpec.
func (in *PolarDBXBackupScheduleSpec) DeepCopy() *PolarDBXBackupScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupScheduleStatus) DeepCopyInto(out *PolarDBXBackupScheduleStatus) {
	*out = *in
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.NextBackupTime != nil {
		in, out := &in.NextBackupTime, &out.NextBackupTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupScheduleStatus.
func (in *PolarDBXBackupScheduleStatus) DeepCopy() *PolarDBXBackupScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupSpec) DeepCopyInto(out *PolarDBXBackupSpec) {
	*out = *in
	out.Cluster = in.Cluster
	out.RetentionTime = in.RetentionTime
	out.StorageProvider = in.StorageProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupSpec.
func (in *PolarDBXBackupSpec) DeepCopy() *PolarDBXBackupSpec {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXBackupStatus) DeepCopyInto(out *PolarDBXBackupStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.XStores != nil {
		in, out := &in.XStores, &out.XStores
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClusterSpecSnapshot != nil {
		in, out := &in.ClusterSpecSnapshot, &out.ClusterSpecSnapshot
		*out = new(PolarDBXClusterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupSetTimestamp != nil {
		in, out := &in.BackupSetTimestamp, &out.BackupSetTimestamp
		*out = make(map[string]*metav1.Time, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.LatestRecoverableTimestamp != nil {
		in, out := &in.LatestRecoverableTimestamp, &out.LatestRecoverableTimestamp
		*out = (*in).DeepCopy()
	}
	if in.CollectStartIndexMap != nil {
		in, out := &in.CollectStartIndexMap, &out.CollectStartIndexMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CollectEndIndexMap != nil {
		in, out := &in.CollectEndIndexMap, &out.CollectEndIndexMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXBackupStatus.
func (in *PolarDBXBackupStatus) DeepCopy() *PolarDBXBackupStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDBXBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXCluster) DeepCopyInto(out *PolarDBXCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXCluster.
func (in *PolarDBXCluster) DeepCopy() *PolarDBXCluster {
	if in == nil {
		return nil
	}
	out := new(PolarDBXCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXClusterKnobs) DeepCopyInto(out *PolarDBXClusterKnobs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXClusterKnobs.
func (in *PolarDBXClusterKnobs) DeepCopy() *PolarDBXClusterKnobs {
	if in == nil {
		return nil
	}
	out := new(PolarDBXClusterKnobs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXClusterKnobs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXClusterKnobsList) DeepCopyInto(out *PolarDBXClusterKnobsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXClusterKnobs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXClusterKnobsList.
func (in *PolarDBXClusterKnobsList) DeepCopy() *PolarDBXClusterKnobsList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXClusterKnobsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXClusterKnobsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXClusterKnobsSpec) DeepCopyInto(out *PolarDBXClusterKnobsSpec) {
	*out = *in
	if in.Knobs != nil {
		in, out := &in.Knobs, &out.Knobs
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXClusterKnobsSpec.
func (in *PolarDBXClusterKnobsSpec) DeepCopy() *PolarDBXClusterKnobsSpec {
	if in == nil {
		return nil
	}
	out := new(PolarDBXClusterKnobsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXClusterKnobsStatus) DeepCopyInto(out *PolarDBXClusterKnobsStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXClusterKnobsStatus.
func (in *PolarDBXClusterKnobsStatus) DeepCopy() *PolarDBXClusterKnobsStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDBXClusterKnobsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXClusterList) DeepCopyInto(out *PolarDBXClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXClusterList.
func (in *PolarDBXClusterList) DeepCopy() *PolarDBXClusterList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXClusterReference) DeepCopyInto(out *PolarDBXClusterReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXClusterReference.
func (in *PolarDBXClusterReference) DeepCopy() *PolarDBXClusterReference {
	if in == nil {
		return nil
	}
	out := new(PolarDBXClusterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXClusterSpec) DeepCopyInto(out *PolarDBXClusterSpec) {
	*out = *in
	out.ProtocolVersion = in.ProtocolVersion
	in.Topology.DeepCopyInto(&out.Topology)
	in.Config.DeepCopyInto(&out.Config)
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]polardbx.PrivilegeItem, len(*in))
		copy(*out, *in)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(polardbx.Security)
		(*in).DeepCopyInto(*out)
	}
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(polardbx.RestoreSpec)
		(*in).DeepCopyInto(*out)
	}
	out.ParameterTemplate = in.ParameterTemplate
	if in.InitReadonly != nil {
		in, out := &in.InitReadonly, &out.InitReadonly
		*out = make([]*polardbx.ReadonlyParam, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(polardbx.ReadonlyParam)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	out.TDE = in.TDE
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXClusterSpec.
func (in *PolarDBXClusterSpec) DeepCopy() *PolarDBXClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PolarDBXClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXClusterStatus) DeepCopyInto(out *PolarDBXClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]polardbx.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.StatusForPrint.DeepCopyInto(&out.StatusForPrint)
	in.ReplicaStatus.DeepCopyInto(&out.ReplicaStatus)
	if in.SpecSnapshot != nil {
		in, out := &in.SpecSnapshot, &out.SpecSnapshot
		*out = new(polardbx.SpecSnapshot)
		(*in).DeepCopyInto(*out)
	}
	in.RestartingPods.DeepCopyInto(&out.RestartingPods)
	if in.PitrStatus != nil {
		in, out := &in.PitrStatus, &out.PitrStatus
		*out = new(polardbx.PitrStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXClusterStatus.
func (in *PolarDBXClusterStatus) DeepCopy() *PolarDBXClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDBXClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXLogCollector) DeepCopyInto(out *PolarDBXLogCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXLogCollector.
func (in *PolarDBXLogCollector) DeepCopy() *PolarDBXLogCollector {
	if in == nil {
		return nil
	}
	out := new(PolarDBXLogCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXLogCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXLogCollectorList) DeepCopyInto(out *PolarDBXLogCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXLogCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXLogCollectorList.
func (in *PolarDBXLogCollectorList) DeepCopy() *PolarDBXLogCollectorList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXLogCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXLogCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXMonitor) DeepCopyInto(out *PolarDBXMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXMonitor.
func (in *PolarDBXMonitor) DeepCopy() *PolarDBXMonitor {
	if in == nil {
		return nil
	}
	out := new(PolarDBXMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXMonitorList) DeepCopyInto(out *PolarDBXMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXMonitorList.
func (in *PolarDBXMonitorList) DeepCopy() *PolarDBXMonitorList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXMonitorSpec) DeepCopyInto(out *PolarDBXMonitorSpec) {
	*out = *in
	out.MonitorInterval = in.MonitorInterval
	out.ScrapeTimeout = in.ScrapeTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXMonitorSpec.
func (in *PolarDBXMonitorSpec) DeepCopy() *PolarDBXMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(PolarDBXMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXMonitorStatus) DeepCopyInto(out *PolarDBXMonitorStatus) {
	*out = *in
	if in.MonitorSpecSnapshot != nil {
		in, out := &in.MonitorSpecSnapshot, &out.MonitorSpecSnapshot
		*out = new(PolarDBXMonitorSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXMonitorStatus.
func (in *PolarDBXMonitorStatus) DeepCopy() *PolarDBXMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDBXMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXParameter) DeepCopyInto(out *PolarDBXParameter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXParameter.
func (in *PolarDBXParameter) DeepCopy() *PolarDBXParameter {
	if in == nil {
		return nil
	}
	out := new(PolarDBXParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXParameter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXParameterList) DeepCopyInto(out *PolarDBXParameterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXParameterList.
func (in *PolarDBXParameterList) DeepCopy() *PolarDBXParameterList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXParameterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXParameterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXParameterSpec) DeepCopyInto(out *PolarDBXParameterSpec) {
	*out = *in
	in.NodeType.DeepCopyInto(&out.NodeType)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXParameterSpec.
func (in *PolarDBXParameterSpec) DeepCopy() *PolarDBXParameterSpec {
	if in == nil {
		return nil
	}
	out := new(PolarDBXParameterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXParameterStatus) DeepCopyInto(out *PolarDBXParameterStatus) {
	*out = *in
	if in.PrevParameterSpecSnapshot != nil {
		in, out := &in.PrevParameterSpecSnapshot, &out.PrevParameterSpecSnapshot
		*out = new(PolarDBXParameterSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ParameterSpecSnapshot != nil {
		in, out := &in.ParameterSpecSnapshot, &out.ParameterSpecSnapshot
		*out = new(PolarDBXParameterSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXParameterStatus.
func (in *PolarDBXParameterStatus) DeepCopy() *PolarDBXParameterStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDBXParameterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXParameterTemplate) DeepCopyInto(out *PolarDBXParameterTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXParameterTemplate.
func (in *PolarDBXParameterTemplate) DeepCopy() *PolarDBXParameterTemplate {
	if in == nil {
		return nil
	}
	out := new(PolarDBXParameterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXParameterTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXParameterTemplateList) DeepCopyInto(out *PolarDBXParameterTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolarDBXParameterTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXParameterTemplateList.
func (in *PolarDBXParameterTemplateList) DeepCopy() *PolarDBXParameterTemplateList {
	if in == nil {
		return nil
	}
	out := new(PolarDBXParameterTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolarDBXParameterTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXParameterTemplateSpec) DeepCopyInto(out *PolarDBXParameterTemplateSpec) {
	*out = *in
	in.NodeType.DeepCopyInto(&out.NodeType)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXParameterTemplateSpec.
func (in *PolarDBXParameterTemplateSpec) DeepCopy() *PolarDBXParameterTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PolarDBXParameterTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXParameterTemplateStatus) DeepCopyInto(out *PolarDBXParameterTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXParameterTemplateStatus.
func (in *PolarDBXParameterTemplateStatus) DeepCopy() *PolarDBXParameterTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDBXParameterTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDbXBinlogPodStatus) DeepCopyInto(out *PolarDbXBinlogPodStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDbXBinlogPodStatus.
func (in *PolarDbXBinlogPodStatus) DeepCopy() *PolarDbXBinlogPodStatus {
	if in == nil {
		return nil
	}
	out := new(PolarDbXBinlogPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreBinlogSource) DeepCopyInto(out *RestoreBinlogSource) {
	*out = *in
	if in.StorageProvider != nil {
		in, out := &in.StorageProvider, &out.StorageProvider
		*out = new(polardbx.BackupStorageProvider)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreBinlogSource.
func (in *RestoreBinlogSource) DeepCopy() *RestoreBinlogSource {
	if in == nil {
		return nil
	}
	out := new(RestoreBinlogSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemTask) DeepCopyInto(out *SystemTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemTask.
func (in *SystemTask) DeepCopy() *SystemTask {
	if in == nil {
		return nil
	}
	out := new(SystemTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemTaskList) DeepCopyInto(out *SystemTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemTaskList.
func (in *SystemTaskList) DeepCopy() *SystemTaskList {
	if in == nil {
		return nil
	}
	out := new(SystemTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemTaskSpec) DeepCopyInto(out *SystemTaskSpec) {
	*out = *in
	in.CnResources.DeepCopyInto(&out.CnResources)
	in.DnResources.DeepCopyInto(&out.DnResources)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemTaskSpec.
func (in *SystemTaskSpec) DeepCopy() *SystemTaskSpec {
	if in == nil {
		return nil
	}
	out := new(SystemTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemTaskStatus) DeepCopyInto(out *SystemTaskStatus) {
	*out = *in
	if in.StBalanceResourceStatus != nil {
		in, out := &in.StBalanceResourceStatus, &out.StBalanceResourceStatus
		*out = new(systemtask.StBalanceResourceStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemTaskStatus.
func (in *SystemTaskStatus) DeepCopy() *SystemTaskStatus {
	if in == nil {
		return nil
	}
	out := new(SystemTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TDE) DeepCopyInto(out *TDE) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TDE.
func (in *TDE) DeepCopy() *TDE {
	if in == nil {
		return nil
	}
	out := new(TDE)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateNode) DeepCopyInto(out *TemplateNode) {
	*out = *in
	if in.ParamList != nil {
		in, out := &in.ParamList, &out.ParamList
		*out = make([]TemplateParams, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateNode.
func (in *TemplateNode) DeepCopy() *TemplateNode {
	if in == nil {
		return nil
	}
	out := new(TemplateNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateNodeType) DeepCopyInto(out *TemplateNodeType) {
	*out = *in
	in.CN.DeepCopyInto(&out.CN)
	in.DN.DeepCopyInto(&out.DN)
	in.GMS.DeepCopyInto(&out.GMS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateNodeType.
func (in *TemplateNodeType) DeepCopy() *TemplateNodeType {
	if in == nil {
		return nil
	}
	out := new(TemplateNodeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateParams) DeepCopyInto(out *TemplateParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateParams.
func (in *TemplateParams) DeepCopy() *TemplateParams {
	if in == nil {
		return nil
	}
	out := new(TemplateParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStore) DeepCopyInto(out *XStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStore.
func (in *XStore) DeepCopy() *XStore {
	if in == nil {
		return nil
	}
	out := new(XStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreBackup) DeepCopyInto(out *XStoreBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreBackup.
func (in *XStoreBackup) DeepCopy() *XStoreBackup {
	if in == nil {
		return nil
	}
	out := new(XStoreBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XStoreBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreBackupBinlog) DeepCopyInto(out *XStoreBackupBinlog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreBackupBinlog.
func (in *XStoreBackupBinlog) DeepCopy() *XStoreBackupBinlog {
	if in == nil {
		return nil
	}
	out := new(XStoreBackupBinlog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XStoreBackupBinlog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreBackupBinlogList) DeepCopyInto(out *XStoreBackupBinlogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XStoreBackupBinlog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreBackupBinlogList.
func (in *XStoreBackupBinlogList) DeepCopy() *XStoreBackupBinlogList {
	if in == nil {
		return nil
	}
	out := new(XStoreBackupBinlogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XStoreBackupBinlogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreBackupBinlogSpec) DeepCopyInto(out *XStoreBackupBinlogSpec) {
	*out = *in
	out.RemoteExpireLogHours = in.RemoteExpireLogHours
	out.LocalExpireLogHours = in.LocalExpireLogHours
	out.StorageProvider = in.StorageProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreBackupBinlogSpec.
func (in *XStoreBackupBinlogSpec) DeepCopy() *XStoreBackupBinlogSpec {
	if in == nil {
		return nil
	}
	out := new(XStoreBackupBinlogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreBackupBinlogStatus) DeepCopyInto(out *XStoreBackupBinlogStatus) {
	*out = *in
	if in.LastDeletedFiles != nil {
		in, out := &in.LastDeletedFiles, &out.LastDeletedFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreBackupBinlogStatus.
func (in *XStoreBackupBinlogStatus) DeepCopy() *XStoreBackupBinlogStatus {
	if in == nil {
		return nil
	}
	out := new(XStoreBackupBinlogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreBackupList) DeepCopyInto(out *XStoreBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XStoreBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreBackupList.
func (in *XStoreBackupList) DeepCopy() *XStoreBackupList {
	if in == nil {
		return nil
	}
	out := new(XStoreBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XStoreBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreBackupSpec) DeepCopyInto(out *XStoreBackupSpec) {
	*out = *in
	out.XStore = in.XStore
	out.RetentionTime = in.RetentionTime
	out.StorageProvider = in.StorageProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreBackupSpec.
func (in *XStoreBackupSpec) DeepCopy() *XStoreBackupSpec {
	if in == nil {
		return nil
	}
	out := new(XStoreBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreBackupStatus) DeepCopyInto(out *XStoreBackupStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.BackupSetTimestamp != nil {
		in, out := &in.BackupSetTimestamp, &out.BackupSetTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreBackupStatus.
func (in *XStoreBackupStatus) DeepCopy() *XStoreBackupStatus {
	if in == nil {
		return nil
	}
	out := new(XStoreBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreFollower) DeepCopyInto(out *XStoreFollower) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreFollower.
func (in *XStoreFollower) DeepCopy() *XStoreFollower {
	if in == nil {
		return nil
	}
	out := new(XStoreFollower)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XStoreFollower) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreFollowerList) DeepCopyInto(out *XStoreFollowerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XStoreFollower, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreFollowerList.
func (in *XStoreFollowerList) DeepCopy() *XStoreFollowerList {
	if in == nil {
		return nil
	}
	out := new(XStoreFollowerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XStoreFollowerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreFollowerSpec) DeepCopyInto(out *XStoreFollowerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreFollowerSpec.
func (in *XStoreFollowerSpec) DeepCopy() *XStoreFollowerSpec {
	if in == nil {
		return nil
	}
	out := new(XStoreFollowerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreFollowerStatus) DeepCopyInto(out *XStoreFollowerStatus) {
	*out = *in
	if in.ToCleanHostPathVolume != nil {
		in, out := &in.ToCleanHostPathVolume, &out.ToCleanHostPathVolume
		*out = new(xstore.HostPathVolume)
		**out = **in
	}
	if in.FlowFlags != nil {
		in, out := &in.FlowFlags, &out.FlowFlags
		*out = make([]FlowFlagType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreFollowerStatus.
func (in *XStoreFollowerStatus) DeepCopy() *XStoreFollowerStatus {
	if in == nil {
		return nil
	}
	out := new(XStoreFollowerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreList) DeepCopyInto(out *XStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreList.
func (in *XStoreList) DeepCopy() *XStoreList {
	if in == nil {
		return nil
	}
	out := new(XStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreReference) DeepCopyInto(out *XStoreReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreReference.
func (in *XStoreReference) DeepCopy() *XStoreReference {
	if in == nil {
		return nil
	}
	out := new(XStoreReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreRestoreFrom) DeepCopyInto(out *XStoreRestoreFrom) {
	*out = *in
	if in.BackupSelector != nil {
		in, out := &in.BackupSelector, &out.BackupSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreRestoreFrom.
func (in *XStoreRestoreFrom) DeepCopy() *XStoreRestoreFrom {
	if in == nil {
		return nil
	}
	out := new(XStoreRestoreFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreRestoreSpec) DeepCopyInto(out *XStoreRestoreSpec) {
	*out = *in
	in.From.DeepCopyInto(&out.From)
	if in.StorageProvider != nil {
		in, out := &in.StorageProvider, &out.StorageProvider
		*out = new(polardbx.BackupStorageProvider)
		**out = **in
	}
	if in.BinlogSource != nil {
		in, out := &in.BinlogSource, &out.BinlogSource
		*out = new(RestoreBinlogSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreRestoreSpec.
func (in *XStoreRestoreSpec) DeepCopy() *XStoreRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(XStoreRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreSpec) DeepCopyInto(out *XStoreSpec) {
	*out = *in
	if in.ServiceLabels != nil {
		in, out := &in.ServiceLabels, &out.ServiceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]xstore.Privilege, len(*in))
		copy(*out, *in)
	}
	in.Topology.DeepCopyInto(&out.Topology)
	in.Config.DeepCopyInto(&out.Config)
	out.ParameterTemplate = in.ParameterTemplate
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(XStoreRestoreSpec)
		(*in).DeepCopyInto(*out)
	}
	out.TDE = in.TDE
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreSpec.
func (in *XStoreSpec) DeepCopy() *XStoreSpec {
	if in == nil {
		return nil
	}
	out := new(XStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreStatus) DeepCopyInto(out *XStoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]xstore.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BoundVolumes != nil {
		in, out := &in.BoundVolumes, &out.BoundVolumes
		*out = make(map[string]*xstore.HostPathVolume, len(*in))
		for key, val := range *in {
			var outVal *xstore.HostPathVolume
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(xstore.HostPathVolume)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.LastVolumeSizeUpdateTime != nil {
		in, out := &in.LastVolumeSizeUpdateTime, &out.LastVolumeSizeUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.ObservedTopology != nil {
		in, out := &in.ObservedTopology, &out.ObservedTopology
		*out = new(xstore.Topology)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedConfig != nil {
		in, out := &in.ObservedConfig, &out.ObservedConfig
		*out = new(xstore.Config)
		(*in).DeepCopyInto(*out)
	}
	if in.LastLogPurgeTime != nil {
		in, out := &in.LastLogPurgeTime, &out.LastLogPurgeTime
		*out = (*in).DeepCopy()
	}
	if in.PodPorts != nil {
		in, out := &in.PodPorts, &out.PodPorts
		*out = make(map[string]xstore.PodPorts, len(*in))
		for key, val := range *in {
			var outVal map[string]int32
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(xstore.PodPorts, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	in.RestartingPods.DeepCopyInto(&out.RestartingPods)
	if in.PitrStatus != nil {
		in, out := &in.PitrStatus, &out.PitrStatus
		*out = new(xstore.PitrStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreStatus.
func (in *XStoreStatus) DeepCopy() *XStoreStatus {
	if in == nil {
		return nil
	}
	out := new(XStoreStatus)
	in.DeepCopyInto(out)
	return out
}
