clusterDefaults:
  version: latest
  images:
    galaxysql: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-sql
    galaxyengine: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-engine-2.0
    galaxycdc: polardbx-opensource-registry.cn-beijing.cr.aliyuncs.com/polardbx/polardbx-cdc
    
imagePullSecrets:
  - name: myregcred2