{
 "title": "PolarDB-X Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(polardbx_up, namespace)"
    }
   },
   {
    "name": "polardbx",
    "query": {
     "query": "label_values(polardbx_up{cluster=\"$cluster\", namespace=\"$namespace\"}, polardbx_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resource Overview",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}\n)\n/sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)",
     "legendFormat": "CPU (CN)"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}\n)\n/sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)\n",
     "legendFormat": "MEM (CN)"
    },
    {
     "expr": "sum(\n    polardbx_container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n    group_left() (sum (mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\",xstore_role=\"leader\"} > 0) by (namespace, pod))\n)/\nsum(\n    kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n    group_left() (sum (mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\",xstore_role=\"leader\"} > 0) by (namespace, pod))\n)",
     "legendFormat": "CPU (DN)"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() (sum (mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"} > 0) by (namespace, pod))\n)/\nsum(\n    kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n    group_left() (sum (mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"} > 0) by (namespace, pod))\n)",
     "legendFormat": "MEM (DN)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[1m])\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}\n)",
     "legendFormat": "Recv/s"
    },
    {
     "expr": "sum(\n irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[1m])\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}\n)",
     "legendFormat": "Sent/s"
    }
   ]
  },
  {
   "title": "QPS (Logical)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(polardbx_stats_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Logical"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(polardbx_stats_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "QPS (Logical)"
    },
    {
     "expr": "sum(irate(polardbx_stats_physical_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "QPS (Physical)"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stats_best_effort_transaction_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) +\n\nsum(rate(polardbx_stats_xa_transaction_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) +\n\nsum(rate(polardbx_stats_tso_transaction_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) ",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stats_error_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Response Time (Logical)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(delta(polardbx_stats_request_time_cost_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) / (sum(delta (polardbx_stats_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) + 1) / 1000",
     "legendFormat": "Logical"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(polardbx_stats_request_time_cost_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) / (sum(delta (polardbx_stats_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) + 1) / 1000",
     "legendFormat": "RT (Logical)"
    },
    {
     "expr": "sum(delta(polardbx_stats_physical_request_time_cost_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) / (sum(delta (polardbx_stats_physical_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) + 1) / 1000",
     "legendFormat": "RT (Physical)"
    }
   ]
  },
  {
   "title": "Connections/Threads",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(polardbx_stats_active_connections{polardbx_name=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "Connections"
    },
    {
     "expr": "sum(polardbx_stats_running_count{polardbx_name=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "Threads (Running)"
    }
   ]
  },
  { "title": "Global Meta Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GMS",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod, xstore_name) (mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"})",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum by (pod, node) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)",
     "legendFormat": "CPU (Limit)"
    },
    {
     "expr": "sum by (pod) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"})\n/ sum by (pod) (\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)",
     "legendFormat": "CPU %"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)",
     "legendFormat": "MEM"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)\n/\nsum by (pod) (\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_bytes_sent{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"}[30s]))"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_bytes_received{polardbx_name=\"$polardbx\", polardbx_role=\"gms\", namespace=\"$namespace\", xstore_role=\"leader\"}[30s]))"
    }
   ]
  },
  { "title": "Compute Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Compute Nodes",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (pod) (polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum by (pod, node) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)",
     "legendFormat": "CPU (Limit)"
    },
    {
     "expr": "sum by (pod) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"})\n/ sum by (pod) (\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)",
     "legendFormat": "CPU %"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)",
     "legendFormat": "MEM"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)\n/\nsum by (pod) (\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)"
    },
    {
     "expr": "sum by (pod) (\n irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[1m])\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)",
     "legendFormat": "Network (Recv)/s"
    },
    {
     "expr": "sum by (pod) (\n irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[1m])\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)",
     "legendFormat": "Network (Sent)/s"
    }
   ]
  },
  {
   "title": "CPU (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "CPU % (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)\n/sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)",
     "legendFormat": "avg cpu %"
    }
   ]
  },
  {
   "title": "Memory (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\ngroup_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"})\n",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Memory % (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)\n/sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n)\n",
     "legendFormat": "avg mem %"
    }
   ]
  },
  {
   "title": "CPU (CN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU % (CN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n) by (pod)\n/sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory (CN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\ngroup_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory % (CN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n) by (pod)\n/sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cn\"}\n) by (pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stats_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "qps (logical)"
    },
    {
     "expr": "sum(rate(polardbx_stats_physical_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "qps (physical)"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(delta(polardbx_stats_request_time_cost_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) / (sum(delta (polardbx_stats_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) + 1) / 1000",
     "legendFormat": "rt (logical)"
    },
    {
     "expr": "sum(delta(polardbx_stats_physical_request_time_cost_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) / (sum(delta (polardbx_stats_physical_request_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[30s])) + 1) / 1000",
     "legendFormat": "rt (physical)"
    }
   ]
  },
  {
   "title": "Connections / Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(polardbx_stats_active_connections{polardbx_name=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(polardbx_stats_running_count{polardbx_name=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "threads (running)"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(idelta(polardbx_jvmstats_gc_collector_invocation_count{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m])) by (type)",
     "legendFormat": "count - {{ type }}"
    },
    {
     "expr": "sum(idelta(polardbx_jvmstats_gc_collector_time_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]) / (idelta(polardbx_jvmstats_gc_collector_invocation_count{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]) + 1)) by (type)",
     "legendFormat": "time - {{ type }}"
    }
   ]
  },
  {
   "title": "Connection Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stc_connection_error_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "connection error"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(polardbx_stats_best_effort_transaction_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "best effort"
    },
    {
     "expr": "sum(rate(polardbx_stats_xa_transaction_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "xa"
    },
    {
     "expr": "sum(rate(polardbx_stats_tso_transaction_count_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "tso"
    }
   ]
  },
  {
   "title": "Processing Time (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk(5, sum by (schema) (\n    label_replace(\n      rate(polardbx_stc_request_time_cost_total{polardbx_name=\"$polardbx\", namespace=\"$namespace\", appname!~\"__.*__@.*|information_schema@.*|polardbx@.*\"}[1m]),\n      \"schema\",\n      \"$1\",\n      \"appname\",\n      \"(.*)@.*\"\n    )\n  )\n) by (schema)",
     "legendFormat": "{{ schema }}"
    }
   ]
  },
  {
   "title": "Physical Connection (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum by (schema) (\n    label_replace(\n      rate(polardbx_stc_active_physical_connection_count{polardbx_name=\"$polardbx\", namespace=\"$namespace\", appname!~\"__.*__@.*|information_schema@.*|polardbx@.*\"}[1m]),\n      \"schema\",\n      \"$1\",\n      \"appname\",\n      \"(.*)@.*\"\n    )\n  )\n) by (schema)",
     "legendFormat": "active - {{ schema }}"
    },
    {
     "expr": "topk(5, sum by (schema) (\n    label_replace(\n      rate(polardbx_stc_pooling_physical_connection_count{polardbx_name=\"$polardbx\", namespace=\"$namespace\", appname!~\"__.*__@.*|information_schema@.*|polardbx@.*\"}[1m]),\n      \"schema\",\n      \"$1\",\n      \"appname\",\n      \"(.*)@.*\"\n    )\n  )\n) by (schema)",
     "legendFormat": "pooling - {{ schema }}"
    }
   ]
  },
  { "title": "Data Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Data Nodes",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by (pod, xstore_name) (mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"})",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum by (pod, node) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)",
     "legendFormat": "CPU (Limit)"
    },
    {
     "expr": "sum by (pod) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"})\n/ sum by (pod) (\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)",
     "legendFormat": "CPU %"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)",
     "legendFormat": "MEM"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)\n/\nsum by (pod) (\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"}\n)"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_bytes_sent{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"}[30s]))"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_bytes_received{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"}[30s]))"
    }
   ]
  },
  {
   "title": "CPU (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "CPU % (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})\n/\nsum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})",
     "legendFormat": "avg cpu %"
    }
   ]
  },
  {
   "title": "Memory (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Memory % (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})\n/\nsum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})",
     "legendFormat": "avg mem %"
    }
   ]
  },
  {
   "title": "CPU (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "CPU % (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)\n/\nsum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "Memory (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "Memory % (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)\n/\nsum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_queries{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "qps (physical)"
    }
   ]
  },
  {
   "title": "Connections/Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_threads_connected{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(mysql_global_status_threads_running{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "buffer pool size"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "Buffer Pool Dirty/Flush (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_buffer_pool_dirty_pages{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "dirty"
    },
    {
     "expr": "sum(rate(mysql_global_status_buffer_pool_page_changes_total{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "flush"
    }
   ]
  },
  {
   "title": "Row Lock Current Wait (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_row_lock_current_waits{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "current wait"
    }
   ]
  },
  {
   "title": "Logical Reads/Writes (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_buffer_pool_read_requests{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_buffer_pool_write_requests{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "IOPS (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_log_writes{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log writes"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_reads{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data reads"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_fsyncs{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data fsyncs"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_os_log_fsyncs{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log fsyncs"
    }
   ]
  },
  {
   "title": "IO Throughput (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_written{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data written/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_read{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data read/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_os_log_written{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log writtern/s"
    }
   ]
  },
  {
   "title": "Network (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_bytes_received{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "received/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_bytes_sent{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "sent/s"
    }
   ]
  },
  {
   "title": "XA Transactions (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\", command=~\"xa_.*\"}[1m])) by (command)",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Transactions (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{polardbx_name=\"$polardbx\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\", command=~\"begin|commit|rollback\"}[1m])) by (command)",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  { "title": "CDC Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "CDC Nodes",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum by (pod) (polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\"})",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum by (pod, node) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)",
     "legendFormat": "CPU (Limit)"
    },
    {
     "expr": "sum by (pod) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"})\n/ sum by (pod) (\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)",
     "legendFormat": "CPU %"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)",
     "legendFormat": "MEM"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)\n/\nsum by (pod) (\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)"
    },
    {
     "expr": "sum by (pod) (\n irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[1m])\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)",
     "legendFormat": "Network (Recv)/s"
    },
    {
     "expr": "sum by (pod) (\n irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[1m])\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)",
     "legendFormat": "Network (Sent)/s"
    }
   ]
  },
  {
   "title": "CPU (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "CPU % (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)\n/sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)",
     "legendFormat": "avg cpu %"
    }
   ]
  },
  {
   "title": "Memory (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\ngroup_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"})\n",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Memory % (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)\n/sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n)\n",
     "legendFormat": "avg mem %"
    }
   ]
  },
  {
   "title": "CPU (CDC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU % (CDC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n) by (pod)\n/sum(\n  kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory (CDC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\ngroup_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory % (CDC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n) by (pod)\n/sum(\n  kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}\n) by (pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Delay(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "polardbx_cdc_dumper_delay_in_millisecond{namespace=\"$namespace\", container=\"exporter\"}\n* on(namespace,pod)\ngroup_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Dumper Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "polardbx_cdc_dumper_jvm_heap_usage{namespace=\"$namespace\", container=\"exporter\"}\n* on(namespace,pod)\ngroup_left() polardbx_cdc_up{polardbx_name=\"$polardbx\", namespace=\"$namespace\", polardbx_role=\"cdc\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}