{
 "title": "XStore Overview",
 "description": "PolarDB-X standard dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(mysql_up, namespace)"
    }
   },
   {
    "name": "xstore",
    "query": {
     "query": "label_values(mysql_up{cluster=\"$cluster\", namespace=\"$namespace\"},xstore_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resource Overview",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n    group_left() (sum (mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\",xstore_role=\"leader\"} > 0) by (namespace, pod))\n)/\nsum(\n    kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"cpu\", unit=\"core\"}\n  * on(namespace,pod)\n    group_left() (sum (mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\",xstore_role=\"leader\"} > 0) by (namespace, pod))\n)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() (sum (mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"} > 0) by (namespace, pod))\n)/\nsum(\n    kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"memory\", unit=\"byte\"}\n  * on(namespace,pod)\n    group_left() (sum (mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\", xstore_role=\"leader\"} > 0) by (namespace, pod))\n)",
     "legendFormat": "MEM"
    }
   ]
  },
  {
   "title": "Network",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[1m])\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\"}\n)",
     "legendFormat": "Recv/s"
    },
    {
     "expr": "sum(\n irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[1m])\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\"}\n)",
     "legendFormat": "Sent/s"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(mysql_global_status_queries{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "Logical"
    }
   ]
  },
  {
   "title": "Buffer Pool Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}) by (xstore_name)",
     "legendFormat": "Logical"
    }
   ]
  },
  {
   "title": "Connections/Threads",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum(mysql_global_status_threads_running{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})\n",
     "legendFormat": "Threads(Running)"
    },
    {
     "expr": "  sum(mysql_global_status_threads_connected{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "Threads(Connected)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_uptime{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "Logical"
    }
   ]
  },
  { "title": "Data Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Data Nodes",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod, xstore_name, xstore_role) (mysql_up{xstore_name=\"$xstore_name\", polardbx_role=\"dn\", namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (pod, node) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"cpu\", unit=\"core\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"}\n)",
     "legendFormat": "CPU (Limit)"
    },
    {
     "expr": "sum by (pod) (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n  * on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"})\n/ sum by (pod) (\n  kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"cpu\", unit=\"core\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"}\n)",
     "legendFormat": "CPU %"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"}\n)",
     "legendFormat": "MEM"
    },
    {
     "expr": "sum by (pod) (\n  kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"memory\", unit=\"byte\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"}\n)"
    },
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n  * on(namespace,pod)\n    group_left() mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"}\n)\n/\nsum by (pod) (\n  kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"memory\", unit=\"byte\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"}\n)"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_bytes_sent{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"}[1m]))"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_bytes_received{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"}[1m]))"
    },
    {
     "expr": "sum by(pod, xstore_role) (mysql_up{xstore_name=\"$xstore\", polardbx_role=\"dn\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", xstore_role=\"leader\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "CPU % (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})\n/\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"cpu\", unit=\"core\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})",
     "legendFormat": "avg cpu %"
    }
   ]
  },
  {
   "title": "Memory (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", xstore_role=\"leader\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Memory % (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})\n/\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"memory\", unit=\"byte\"}\n* on(namespace,pod)\n  group_left() mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"})",
     "legendFormat": "avg mem %"
    }
   ]
  },
  {
   "title": "CPU (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "CPU % (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(polardbx_container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\", container=\"engine\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)\n/\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"cpu\", unit=\"core\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "Memory (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "Memory % (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"engine\", id=~\"^/kubepods.*\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)\n/\nsum(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"engine\", resource=\"memory\", unit=\"byte\"}\n* on(namespace,pod)\n  group_left(xstore_name) mysql_up{xstore_name=\"$xstore\", namespace=\"$namespace\", polardbx_role=\"dn\", xstore_role=\"leader\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_queries{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "qps (physical)"
    }
   ]
  },
  {
   "title": "Connections/Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_threads_connected{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(mysql_global_status_threads_running{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "buffer pool size"
    }
   ]
  },
  {
   "title": "Buffer Pool Size (DN)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_buffer_pool_bytes_data{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}) by (xstore_name)",
     "legendFormat": "{{ xstore_name }}"
    }
   ]
  },
  {
   "title": "Buffer Pool Dirty/Flush (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_buffer_pool_dirty_pages{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "dirty"
    },
    {
     "expr": "sum(rate(mysql_global_status_buffer_pool_page_changes_total{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[10m]))",
     "legendFormat": "flush"
    }
   ]
  },
  {
   "title": "Row Lock Current Wait (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_global_status_innodb_row_lock_current_waits{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"})",
     "legendFormat": "current wait"
    }
   ]
  },
  {
   "title": "Logical Reads/Writes (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_buffer_pool_read_requests{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_buffer_pool_write_requests{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "IOPS (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_log_writes{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log writes"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_reads{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data reads"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_fsyncs{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data fsyncs"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_os_log_fsyncs{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log fsyncs"
    }
   ]
  },
  {
   "title": "IO Throughput (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_written{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data written/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_data_read{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "data read/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_innodb_os_log_written{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "log writtern/s"
    }
   ]
  },
  {
   "title": "Network (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_bytes_received{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "received/s"
    },
    {
     "expr": "sum(rate(mysql_global_status_bytes_sent{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "sent/s"
    }
   ]
  },
  {
   "title": "XA Transactions (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\", command=~\"xa_.*\"}[1m])) by (command)",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Transactions (Total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{xstore_name=\"$xstore\", polardbx_role=\"dn\", xstore_role=\"leader\", namespace=\"$namespace\", command=~\"begin|commit|rollback\"}[1m])) by (command)",
     "legendFormat": "{{ command }}"
    }
   ]
  }
 ]
}