import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideNoopAnimations } from '@angular/platform-browser/animations';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import { provideNzI18n, zh_CN } from 'ng-zorro-antd/i18n';
import { provideNzConfig } from 'ng-zorro-antd/core/config';
import { LOCALE_ID } from '@angular/core';
import { registerLocaleData } from '@angular/common';
import zh from '@angular/common/locales/zh';
import { NzMessageModule } from 'ng-zorro-antd/message';
import { NzModalModule } from 'ng-zorro-antd/modal';

registerLocaleData(zh);
import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  AimOutline,
  AppstoreOutline,
  ApartmentOutline,
  AreaChartOutline,
  ArrowRightOutline,
  ArrowLeftOutline,
  AlignLeftOutline,
  BarsOutline,
  CloudUploadOutline,
  CloudFill,
  UndoOutline,
  DatabaseOutline,
  DatabaseFill,
  SettingOutline,
  SaveOutline,
  CalendarOutline,
  CheckOutline,
  CheckCircleTwoTone,
  CloseCircleTwoTone,
  FileTextOutline,
  FileOutline,
  FileDoneOutline,
  FolderOpenOutline,
  FullscreenOutline,
  HddOutline,
  DeploymentUnitOutline,
  DashboardOutline,
  SlidersOutline,
  ProfileOutline,
  FileSearchOutline,
  HistoryOutline,
  ToolOutline,
  ReloadOutline,
  RedoOutline,
  LoadingOutline,
  SyncOutline,
  StopOutline,
  CloudDownloadOutline,
  CloudServerOutline,
  InboxOutline,
  SafetyOutline,
  SafetyCertificateOutline,
  GlobalOutline,
  ClockCircleOutline,
  CheckCircleOutline,
  CheckCircleFill,
  ExclamationCircleOutline,
  ExclamationCircleFill,
  CloseCircleOutline,
  CloseCircleFill,
  CloseOutline,
  PlusOutline,
  MoreOutline,
  EyeOutline,
  EditOutline,
  DeleteOutline,
  InfoCircleOutline,
  InfoCircleFill,
  PlayCircleOutline,
  CopyOutline,
  DownloadOutline,
  LinkOutline,
  SearchOutline,
  NotificationOutline,
  BellOutline,
  LoginOutline,
  LogoutOutline,
  WarningOutline,
  WarningFill,
  AuditOutline,
  LeftOutline,
  RightOutline,
  CloudOutline,
  ShareAltOutline,
  FilterOutline,
  DownOutline,
  TagOutline,
  TeamOutline,
  BookOutline,
  ClusterOutline,
  FieldTimeOutline,
  QuestionCircleOutline,
  ExportOutline,
  SettingTwoTone,
  BugOutline,
  BuildOutline,
  ContainerOutline,
  DingdingOutline,
  FireOutline,
  HighlightOutline,
  MailOutline,
  MedicineBoxOutline,
  MinusCircleOutline,
  PlusCircleOutline,
  PauseCircleOutline,
  ReadOutline,
  RocketOutline,
  RocketTwoTone,
  RobotOutline,
  RollbackOutline,
  ThunderboltOutline,
  CodeOutline,
  DesktopOutline,
  ControlOutline,
  UnorderedListOutline
} from '@ant-design/icons-angular/icons';
import { PauseOutline, ExperimentOutline, LineChartOutline, BarChartOutline, FileAddOutline, HeartOutline, BulbOutline, AlertOutline } from '@ant-design/icons-angular/icons';

import { routes } from './app.routes';
import { authInterceptor } from './interceptors/auth.interceptor';
import { kubeconfigHeaderInterceptor } from './interceptors/kubeconfig.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }), 
    provideRouter(routes),
    provideHttpClient(withInterceptors([
      authInterceptor,
      kubeconfigHeaderInterceptor
    ])),
    provideNoopAnimations(),
    provideNzI18n(zh_CN),
    { provide: LOCALE_ID, useValue: 'zh-cn' },
    provideNzConfig({
      tabs: { nzAnimated: false }
    }),
    importProvidersFrom(NzMessageModule, NzModalModule),
    provideNzIcons([
      MenuFoldOutline,
      MenuUnfoldOutline,
      AppstoreOutline,
      ArrowRightOutline,
      ArrowLeftOutline,
      CloudUploadOutline,
      CloudFill,
      UndoOutline,
      DatabaseOutline,
      DatabaseFill,
      SettingOutline,
      SaveOutline,
      CalendarOutline,
      CheckOutline,
      FileTextOutline,
      HddOutline,
      DeploymentUnitOutline,
      DashboardOutline,
      SlidersOutline,
      ProfileOutline,
      FileSearchOutline,
      HistoryOutline,
      ToolOutline,
      ReloadOutline,
      RedoOutline,
      LoadingOutline,
      SyncOutline,
      CloudDownloadOutline,
      CloudServerOutline,
      InboxOutline,
      SafetyOutline,
      SafetyCertificateOutline,
      GlobalOutline,
      ClockCircleOutline,
      CheckCircleOutline,
      CheckCircleFill,
      ExclamationCircleOutline,
      CloseCircleOutline,
      CloseOutline,
      PlusOutline,
      MoreOutline,
      EyeOutline,
      EditOutline,
      DeleteOutline,
      InfoCircleOutline,
      PlayCircleOutline,
      CopyOutline,
      DownloadOutline,
      LinkOutline,
      SearchOutline,
      NotificationOutline,
      BellOutline,
      LoginOutline,
      LogoutOutline,
      WarningOutline,
      AuditOutline,
      LeftOutline,
      RightOutline,
      CloudOutline,
      ShareAltOutline,
      FilterOutline,
      DownOutline,
      TagOutline,
      TeamOutline,
      BookOutline,
      ClusterOutline,
      FieldTimeOutline,
      QuestionCircleOutline,
      ExportOutline,
      SettingTwoTone,
      BugOutline,
      BuildOutline,
      ContainerOutline,
      DingdingOutline,
      FireOutline,
      HighlightOutline,
      MailOutline,
      MedicineBoxOutline,
      MinusCircleOutline,
      PlusCircleOutline,
      PauseCircleOutline,
      ReadOutline,
      RocketOutline,
      RocketTwoTone,
      RollbackOutline,
      ThunderboltOutline,
      CodeOutline,
      DesktopOutline,
      ControlOutline,
      UnorderedListOutline,
      AimOutline,
      ApartmentOutline,
      AreaChartOutline,
      AlignLeftOutline,
      BarsOutline,
      CheckCircleTwoTone,
      CloseCircleTwoTone,
      RobotOutline,
      FileOutline,
      FileDoneOutline,
      FolderOpenOutline,
      FullscreenOutline,
      StopOutline,
      ExclamationCircleFill,
      CloseCircleFill,
      InfoCircleFill,
      WarningFill,
      PauseOutline,
      ExperimentOutline,
      LineChartOutline,
      BarChartOutline,
      FileAddOutline,
      HeartOutline,
      BulbOutline,
      AlertOutline
    ])
  ]
};
