//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 Alibaba Group Holding Limited.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package polardbx

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStorageFilestreamAction) DeepCopyInto(out *BackupStorageFilestreamAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStorageFilestreamAction.
func (in *BackupStorageFilestreamAction) DeepCopy() *BackupStorageFilestreamAction {
	if in == nil {
		return nil
	}
	out := new(BackupStorageFilestreamAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStorageProvider) DeepCopyInto(out *BackupStorageProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStorageProvider.
func (in *BackupStorageProvider) DeepCopy() *BackupStorageProvider {
	if in == nil {
		return nil
	}
	out := new(BackupStorageProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CDCConfig) DeepCopyInto(out *CDCConfig) {
	*out = *in
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CDCConfig.
func (in *CDCConfig) DeepCopy() *CDCConfig {
	if in == nil {
		return nil
	}
	out := new(CDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CDCTemplate) DeepCopyInto(out *CDCTemplate) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CDCTemplate.
func (in *CDCTemplate) DeepCopy() *CDCTemplate {
	if in == nil {
		return nil
	}
	out := new(CDCTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNConfig) DeepCopyInto(out *CNConfig) {
	*out = *in
	if in.Dynamic != nil {
		in, out := &in.Dynamic, &out.Dynamic
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(CNStaticConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ColdDataFileStorage != nil {
		in, out := &in.ColdDataFileStorage, &out.ColdDataFileStorage
		*out = make([]FileStorageInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNConfig.
func (in *CNConfig) DeepCopy() *CNConfig {
	if in == nil {
		return nil
	}
	out := new(CNConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNStaticConfig) DeepCopyInto(out *CNStaticConfig) {
	*out = *in
	if in.ServerProperties != nil {
		in, out := &in.ServerProperties, &out.ServerProperties
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.RPCProtocolVersion = in.RPCProtocolVersion
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNStaticConfig.
func (in *CNStaticConfig) DeepCopy() *CNStaticConfig {
	if in == nil {
		return nil
	}
	out := new(CNStaticConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNTemplate) DeepCopyInto(out *CNTemplate) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNTemplate.
func (in *CNTemplate) DeepCopy() *CNTemplate {
	if in == nil {
		return nil
	}
	out := new(CNTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReplicasStatus) DeepCopyInto(out *ClusterReplicasStatus) {
	*out = *in
	out.GMS = in.GMS
	if in.CN != nil {
		in, out := &in.CN, &out.CN
		*out = new(ReplicasStatus)
		**out = **in
	}
	out.DN = in.DN
	if in.CDC != nil {
		in, out := &in.CDC, &out.CDC
		*out = new(ReplicasStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReplicasStatus.
func (in *ClusterReplicasStatus) DeepCopy() *ClusterReplicasStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterReplicasStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.LastProbeTime != nil {
		in, out := &in.LastProbeTime, &out.LastProbeTime
		*out = (*in).DeepCopy()
	}
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	in.CN.DeepCopyInto(&out.CN)
	in.DN.DeepCopyInto(&out.DN)
	in.CDC.DeepCopyInto(&out.CDC)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNConfig) DeepCopyInto(out *DNConfig) {
	*out = *in
	out.LogPurgeInterval = in.LogPurgeInterval
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNConfig.
func (in *DNConfig) DeepCopy() *DNConfig {
	if in == nil {
		return nil
	}
	out := new(DNConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileStorageInfo) DeepCopyInto(out *FileStorageInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileStorageInfo.
func (in *FileStorageInfo) DeepCopy() *FileStorageInfo {
	if in == nil {
		return nil
	}
	out := new(FileStorageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelectorItem) DeepCopyInto(out *NodeSelectorItem) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelectorItem.
func (in *NodeSelectorItem) DeepCopy() *NodeSelectorItem {
	if in == nil {
		return nil
	}
	out := new(NodeSelectorItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelectorReference) DeepCopyInto(out *NodeSelectorReference) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.NodeSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelectorReference.
func (in *NodeSelectorReference) DeepCopy() *NodeSelectorReference {
	if in == nil {
		return nil
	}
	out := new(NodeSelectorReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterTemplate) DeepCopyInto(out *ParameterTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterTemplate.
func (in *ParameterTemplate) DeepCopy() *ParameterTemplate {
	if in == nil {
		return nil
	}
	out := new(ParameterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PitrStatus) DeepCopyInto(out *PitrStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PitrStatus.
func (in *PitrStatus) DeepCopy() *PitrStatus {
	if in == nil {
		return nil
	}
	out := new(PitrStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolarDBXRestoreFrom) DeepCopyInto(out *PolarDBXRestoreFrom) {
	*out = *in
	if in.BackupSelector != nil {
		in, out := &in.BackupSelector, &out.BackupSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolarDBXRestoreFrom.
func (in *PolarDBXRestoreFrom) DeepCopy() *PolarDBXRestoreFrom {
	if in == nil {
		return nil
	}
	out := new(PolarDBXRestoreFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivilegeItem) DeepCopyInto(out *PrivilegeItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivilegeItem.
func (in *PrivilegeItem) DeepCopy() *PrivilegeItem {
	if in == nil {
		return nil
	}
	out := new(PrivilegeItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadonlyParam) DeepCopyInto(out *ReadonlyParam) {
	*out = *in
	if in.ExtraParams != nil {
		in, out := &in.ExtraParams, &out.ExtraParams
		*out = make(map[string]intstr.IntOrString, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadonlyParam.
func (in *ReadonlyParam) DeepCopy() *ReadonlyParam {
	if in == nil {
		return nil
	}
	out := new(ReadonlyParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaStatusForPrint) DeepCopyInto(out *ReplicaStatusForPrint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaStatusForPrint.
func (in *ReplicaStatusForPrint) DeepCopy() *ReplicaStatusForPrint {
	if in == nil {
		return nil
	}
	out := new(ReplicaStatusForPrint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicasStatus) DeepCopyInto(out *ReplicasStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicasStatus.
func (in *ReplicasStatus) DeepCopy() *ReplicasStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicasStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestartingPods) DeepCopyInto(out *RestartingPods) {
	*out = *in
	if in.ToDeletePod != nil {
		in, out := &in.ToDeletePod, &out.ToDeletePod
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestartingPods.
func (in *RestartingPods) DeepCopy() *RestartingPods {
	if in == nil {
		return nil
	}
	out := new(RestartingPods)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreBinlogSource) DeepCopyInto(out *RestoreBinlogSource) {
	*out = *in
	if in.StorageProvider != nil {
		in, out := &in.StorageProvider, &out.StorageProvider
		*out = new(BackupStorageProvider)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreBinlogSource.
func (in *RestoreBinlogSource) DeepCopy() *RestoreBinlogSource {
	if in == nil {
		return nil
	}
	out := new(RestoreBinlogSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSpec) DeepCopyInto(out *RestoreSpec) {
	*out = *in
	if in.StorageProvider != nil {
		in, out := &in.StorageProvider, &out.StorageProvider
		*out = new(BackupStorageProvider)
		**out = **in
	}
	in.From.DeepCopyInto(&out.From)
	if in.BinlogSource != nil {
		in, out := &in.BinlogSource, &out.BinlogSource
		*out = new(RestoreBinlogSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSpec.
func (in *RestoreSpec) DeepCopy() *RestoreSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Security) DeepCopyInto(out *Security) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLS)
		**out = **in
	}
	if in.EncodeKey != nil {
		in, out := &in.EncodeKey, &out.EncodeKey
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Security.
func (in *Security) DeepCopy() *Security {
	if in == nil {
		return nil
	}
	out := new(Security)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecSnapshot) DeepCopyInto(out *SpecSnapshot) {
	*out = *in
	in.Topology.DeepCopyInto(&out.Topology)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecSnapshot.
func (in *SpecSnapshot) DeepCopy() *SpecSnapshot {
	if in == nil {
		return nil
	}
	out := new(SpecSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatelessTopologyRuleItem) DeepCopyInto(out *StatelessTopologyRuleItem) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(NodeSelectorReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatelessTopologyRuleItem.
func (in *StatelessTopologyRuleItem) DeepCopy() *StatelessTopologyRuleItem {
	if in == nil {
		return nil
	}
	out := new(StatelessTopologyRuleItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusForPrint) DeepCopyInto(out *StatusForPrint) {
	*out = *in
	out.ReplicaStatus = in.ReplicaStatus
	if in.StorageSizeUpdateTime != nil {
		in, out := &in.StorageSizeUpdateTime, &out.StorageSizeUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusForPrint.
func (in *StatusForPrint) DeepCopy() *StatusForPrint {
	if in == nil {
		return nil
	}
	out := new(StatusForPrint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
func (in *TLS) DeepCopy() *TLS {
	if in == nil {
		return nil
	}
	out := new(TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Topology) DeepCopyInto(out *Topology) {
	*out = *in
	in.Rules.DeepCopyInto(&out.Rules)
	in.Nodes.DeepCopyInto(&out.Nodes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Topology.
func (in *Topology) DeepCopy() *Topology {
	if in == nil {
		return nil
	}
	out := new(Topology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyNodeCDC) DeepCopyInto(out *TopologyNodeCDC) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyNodeCDC.
func (in *TopologyNodeCDC) DeepCopy() *TopologyNodeCDC {
	if in == nil {
		return nil
	}
	out := new(TopologyNodeCDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyNodeCN) DeepCopyInto(out *TopologyNodeCN) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyNodeCN.
func (in *TopologyNodeCN) DeepCopy() *TopologyNodeCN {
	if in == nil {
		return nil
	}
	out := new(TopologyNodeCN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyNodeDN) DeepCopyInto(out *TopologyNodeDN) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyNodeDN.
func (in *TopologyNodeDN) DeepCopy() *TopologyNodeDN {
	if in == nil {
		return nil
	}
	out := new(TopologyNodeDN)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyNodeGMS) DeepCopyInto(out *TopologyNodeGMS) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(XStoreTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyNodeGMS.
func (in *TopologyNodeGMS) DeepCopy() *TopologyNodeGMS {
	if in == nil {
		return nil
	}
	out := new(TopologyNodeGMS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyNodes) DeepCopyInto(out *TopologyNodes) {
	*out = *in
	in.GMS.DeepCopyInto(&out.GMS)
	in.CN.DeepCopyInto(&out.CN)
	in.DN.DeepCopyInto(&out.DN)
	if in.CDC != nil {
		in, out := &in.CDC, &out.CDC
		*out = new(TopologyNodeCDC)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyNodes.
func (in *TopologyNodes) DeepCopy() *TopologyNodes {
	if in == nil {
		return nil
	}
	out := new(TopologyNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyRuleComponents) DeepCopyInto(out *TopologyRuleComponents) {
	*out = *in
	if in.CN != nil {
		in, out := &in.CN, &out.CN
		*out = make([]StatelessTopologyRuleItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CDC != nil {
		in, out := &in.CDC, &out.CDC
		*out = make([]StatelessTopologyRuleItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GMS != nil {
		in, out := &in.GMS, &out.GMS
		*out = new(XStoreTopologyRule)
		(*in).DeepCopyInto(*out)
	}
	if in.DN != nil {
		in, out := &in.DN, &out.DN
		*out = new(XStoreTopologyRule)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyRuleComponents.
func (in *TopologyRuleComponents) DeepCopy() *TopologyRuleComponents {
	if in == nil {
		return nil
	}
	out := new(TopologyRuleComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyRules) DeepCopyInto(out *TopologyRules) {
	*out = *in
	if in.Selectors != nil {
		in, out := &in.Selectors, &out.Selectors
		*out = make([]NodeSelectorItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyRules.
func (in *TopologyRules) DeepCopy() *TopologyRules {
	if in == nil {
		return nil
	}
	out := new(TopologyRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreTemplate) DeepCopyInto(out *XStoreTemplate) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
	if in.DiskQuota != nil {
		in, out := &in.DiskQuota, &out.DiskQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreTemplate.
func (in *XStoreTemplate) DeepCopy() *XStoreTemplate {
	if in == nil {
		return nil
	}
	out := new(XStoreTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreTopologyRule) DeepCopyInto(out *XStoreTopologyRule) {
	*out = *in
	if in.Rolling != nil {
		in, out := &in.Rolling, &out.Rolling
		*out = new(XStoreTopologyRuleRolling)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSets != nil {
		in, out := &in.NodeSets, &out.NodeSets
		*out = make([]XStoreTopologyRuleNodeSetItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreTopologyRule.
func (in *XStoreTopologyRule) DeepCopy() *XStoreTopologyRule {
	if in == nil {
		return nil
	}
	out := new(XStoreTopologyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreTopologyRuleNodeSetItem) DeepCopyInto(out *XStoreTopologyRuleNodeSetItem) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(NodeSelectorReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreTopologyRuleNodeSetItem.
func (in *XStoreTopologyRuleNodeSetItem) DeepCopy() *XStoreTopologyRuleNodeSetItem {
	if in == nil {
		return nil
	}
	out := new(XStoreTopologyRuleNodeSetItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XStoreTopologyRuleRolling) DeepCopyInto(out *XStoreTopologyRuleRolling) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(NodeSelectorReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XStoreTopologyRuleRolling.
func (in *XStoreTopologyRuleRolling) DeepCopy() *XStoreTopologyRuleRolling {
	if in == nil {
		return nil
	}
	out := new(XStoreTopologyRuleRolling)
	in.DeepCopyInto(out)
	return out
}
